### ISSUE TITLE
Tag 0.3.5 / build container / push to dockerhub

### ISSUE THREAD

**Issue by jmuhlich** [yfukai/basicpy-docker-mcmicro#26]
It would be great to have a new Docker container with the latest changes. I can of course build myself and push to my own organization on DockerHub but it feels a bit wrong.

**Comment by yfukai** [comment]
Oh I'm sorry for missing this, please wait for a moment.

**Comment by yfukai** [comment]
Ideally it'd be better if we could automate this or make it easy but unfortunately I don't have sufficient time for that for now... I invited you as a collaborator @jmuhlich so that we both can make a release whenever necessary.

**Comment by yfukai** [comment]
The build seems to have failed, I'll check the cause

**Comment by yfukai** [comment]
I resolved the issue and it's now released. I'm sorry for the delay.
