### ISSUE TITLE
Latest changes seem to break Docker container?

### ISSUE THREAD

**Issue by FloWuenne** [yfukai/basicpy-docker-mcmicro#3]
Hi @yfukai ,

I am writing the nf-core module for Basicpy at the moment:
https://github.com/nf-core/modules/pull/3293

The latest update for the docker container seems to have broken the docker container usage. Now when I simply try to run the container in a Gitpod environment, I get the following error:

```
docker run --rm  yfukai/basicpy-docker-mcmicro:latest --cpu
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
exec /opt/main.py: exec format error
```

Maybe you can see if you can reproduce the error on your end? 

Thanks and best,

Florian

**Comment by yfukai** [comment]
Thanks, @FloWuenne, for working on the nf-core integration! 
I believe this is a cross-compilation issue, and it looks the amd64 image is not correctly uploaded... I'll deal with this problem in two or three days.

**Comment by yfukai** [comment]
I believe it's fixed now! @migueLib has changed the arguments in #1, so you might need to change the script accordingly.
I'll also work to publish the package in conda-forge.

**Comment by yfukai** [comment]
Please feel free to re-open.

**Comment by FloWuenne** [comment]
Thanks @yfukai ! The changes to the container worked and thanks to @migueLib changes to the command line, the nf-core module for Basicpy is now merged and available via nf-core modules!

https://github.com/nf-core/modules/pull/3293

**Comment by yfukai** [comment]
Awesome, thank you @FloWuenne !

**Comment by FloWuenne** [comment]
My pleasure! You can now find basicpy in the modules documentation page. If you find any errors or something that doesn't work when testing in nextflow. Let me know!
https://nf-co.re/modules/basicpy
